### ISSUE TITLE
Load errors with latest google-api-client (0.9.23)

### ISSUE THREAD

**Issue by booleanbetrayal** [gimite/google-drive-ruby#248] opened 2017-01-23 19:42 UTC
Getting the following with `gem 'google-api-client (0.9.23)' ...

```
  LoadError: cannot load such file -- google/apis/drive_v3
```

**Comment by Aravind99** [comment] 2017-01-25 07:09
I have same issue but i solved by making the changes below to project

I have migrated to rbenv 2.3.3

```ruby
# In Gemfile
# Use google_drive for documents
gem 'google_drive', '2.1.2'
```

**Comment by gimite** [comment] 2017-01-26 01:19
Hmm I cannot reproduce the issue. Maybe can you retry with google-api-client 0.9.24? Do you have gems/google-api-client-0.9.23/generated/google/apis/drive_v3.rb in your system?

**Comment by gimite** [comment] 2017-02-02 23:59
Closing for now assuming it was fixed by reinstalling the gem or upgrading to 0.9.24. Feel free to reopen if you still encounter the issue after reinstalling the gem or upgrading to 0.9.24.

**Closed by gimite** 2017-02-02 23:59 UTC
