### ISSUE TITLE
Getting Faraday::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed 

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [gimite/google-drive-ruby#237] opened 2016-11-08 12:44 UTC
Hi, 

I am trying out API and getting the ssl error. I followed the instructions at https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md to setup authorization. can you please check ? 

------------------------------------------------------------------------------
2.2.1 :001 > require 'google_drive'
 => true 
2.2.1 :002 > GoogleDrive::Session.from_config(File.expand_path("~/config/g_config.json"))

1. Open this page:
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=6605044332-fndip5mjhkmij71ifip7b923hebkmucu.apps.googleusercontent.com&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=https://www.googleapis.com/auth/drive%20https://spreadsheets.google.com/feeds/

2. Enter the authorization code shown in the page: 4/Y-eS62AssvHXtFXhalv9hQYykY02pMji4StedpFW9As
Faraday::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /Users/himanshu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/himanshu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/himanshu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/himanshu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/himanshu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/himanshu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/himanshu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:960:in `fetch_access_token'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:998:in `fetch_access_token!'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/googleauth-0.5.1/lib/googleauth/signet.rb:69:in `fetch_access_token!'
	from /Users/himanshu/.rvm/gems/ruby-2.2.1/gems/google_drive-2.1.1/lib/google_drive/session.rb:122:in `from_config'
	from (irb):2
2.2.1 :003 > exit
-------------------------------

**Comment by gimite** [comment] 2016-11-08 14:16
Marked as duplicate of #166. The article linked from the issue:
http://railsapps.github.io/openssl-certificate-verify-failed.html
explains some solutions.

**Closed by gimite** 2016-11-08 14:16 UTC

**Comment by jostster** [comment] 2016-11-22 21:03
@gimite this seems to be a bigger issue than what you posted. That did not help me nor has it helped anyone else. We are on windows and have updated to the latest openssl and we still get this error.

**Comment by gimite** [comment] 2016-11-23 05:17
Have you tried https://gist.github.com/fnichol/867550 which is linked from the document?

Anyway I believe it's a general issue of Ruby+Windows+SSL, rather than an issue specific to google-drive-ruby library. So, if it still doesn't fix the issue, it would be better to find solution in StackOverflow or consult Ruby community.

To verify if it's a general issue, you can write Ruby code which fetches any page under https://www.google.com, but make sure that you turn on certification verification.
