### ISSUE TITLE
supress logs 

### ISSUE THREAD

**Issue by kamal-github** [gimite/google-drive-ruby#215] opened 2016-06-28 10:01 UTC
how can we suppress the logs for google spreadsheet in production?

```
</gs:cell></entry><entry gd:etag='&quot;ImA6ClwXUit7&quot;'><id>https://spreadsheets.google.com/feeds/cells/-/omvezn6/R164C1</id><updated>2016-06-28T02:36:36.356Z</updated><app:edited xmlns:app='http://www.w3.org/2007/app'>2016-06-28T02:36:36.356Z</app:edited><category scheme='http://schemas.google.com/spreadsheets/2006' term='http://schemas.google.com/spreadsheets/2006#cell'/><title>A164</title><content>32</content><link rel='self' type='application/atom+xml' href='https://spreadsheets.google.com/feeds/cells/1WHPh1oGMjPn-/omvezn6/private/full/R164C1'/><link rel='edit' type='application/atom+xml' href='https://spreadsheets.google.com/feeds/cells/1WHPh1oGMjPn-/omvezn6/private/full/R164C1'/><gs:cell row='164' col='1' inputValue='32' numericValue='32.0'>32</gs:cell></entry><entry gd:etag='&quot;ImA5WUICFSt7&quot;'><id>https://spreadsheets.google.com/feeds/cells/-pvGPDXo6PvPhoB4V

```

Its showing similar output for every response.

**Comment by gimite** [comment] 2016-07-01 00:47
Hmm I couldn't find code to output such a log at a glance. I also don't see such log when I run the unit test. Are you sure that the log is generated by google_drive library, not by your code?

**Comment by gimite** [comment] 2016-08-08 13:44
Closing for now. Please reopen you still believe it's caused by the library.

**Comment by NickMele** [comment] 2016-09-26 16:57
I am seeing these same logs, if they are not caused by this exact library they are caused by one of its dependencies.

**Comment by kamal-github** [comment] 2016-10-04 14:29
They are mainly feeds coming and flood my rails log.

**Comment by alesthome** [comment] 2016-12-21 22:05
Were you able to figure out how to suppress the logs? I have a small app that is accumulating 20Gbs of production logs a day since I started using this gem.

**Comment by gimite** [comment] 2016-12-22 02:43
It would be really helpful if someone who experience this issue tries to run the test (test/test_google_drive.rb in Github repo) to see if the same issue happens.

Because I cannot reproduce the issue so far.

**Comment by alesthome** [comment] 2017-01-03 16:52
I was running production with :debug as the log level. I changed it to :warn and the issue got resolved. If anyone else runs into this problem, try setting ```config.log_level = :warn``` in production.log (or :info) 
Thanks for the gem, it's been very useful!

**Comment by gimite** [comment] 2017-01-04 07:20
Where does the ```config``` come from? Is it part of some framework?

**Closed** 2017-01-04 16:00 UTC

**Comment by dle** [comment] 2017-06-28 17:22
I'm adding a comment in case anyone has the same problem and is looking for the solution. I was using this gem within Rails and it was outputting way too much logging data. It turns out that the google-api-client dependency of this gem defaults to using the Rails logger when running in a Rails environment. You can create a new logger instance for the Google::Apis to use, so that you don't have to change your whole Rails log level just for the library. Example: https://github.com/google/google-api-ruby-client#logging

**Comment by ineu** [comment] 2021-02-15 11:36
The link above is no longer alive, here's the new one: https://github.com/googleapis/google-api-ruby-client/blob/master/docs/usage-guide.md#logging
